# Generated by Django 5.2.4 on 2025-08-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybudget',
            name='user',
        ),
    ]
