# Generated by Django 5.2.4 on 2025-08-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_monthlybudget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
